name: deposits_app
description: A Flutter app for managing fixed deposits with OCR capabilities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Routing
  go_router: ^16.2.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.1
  firebase_ui_auth: ^1.16.0
  firebase_ui_firestore: ^1.7.1

  # OCR
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.0.4
  camera: ^0.11.2

  # Notifications
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.0

  # Charts & Data Visualization
  fl_chart: ^0.70.0

  # Security & Encryption
  crypto: ^3.0.3
  local_auth: ^2.1.7
  flutter_secure_storage: ^10.0.0-beta.4

  # Data Models & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Utilities
  uuid: ^4.2.1
  intl: ^0.20.2
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0

  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^6.0.0

  # Testing
  mockito: ^5.4.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
